### ISSUE TITLE
Occasional ECONNREFUSED:-1

### ISSUE THREAD

**Issue by stolinski** [xolvio/meteor-cucumber#39] opened 2015-02-13 20:41 UTC
I'm occasionally getting this:

    RuntimeError: RuntimeError
    (ECONNREFUSED:-1) Couldn't connect to selenium server
     Problem: Couldn't connect to selenium server

    Callstack:
     -> init()

Usually after I've already ran tests several times. Restarting my Meteor app does not fix, but restarting my computer fixes temporarily every time. 

On OS X 10.9, xolvio:cucumber 0.3.8

Any ideas?

**Comment by jimmiebtlr** [comment] 2015-02-14 02:07
`xolvio:webdriver` doesn't automatically install webdriver yet.

    npm install selenium-webdriver

**Comment by stolinski** [comment] 2015-02-14 16:53
I saw that, but I was mostly wondering why it will work correctly over and over but suddenly stop working.

**Comment by samhatoum** [comment] 2015-02-15 00:53
Sometimes phantom gets stuck and doing a `pkill -9 phantomjs` helps. I've yet to figure out a way to better manage phantom instances

**Comment by geekyme** [comment] 2015-02-15 04:46
I can confirm the issue is happening for me too. 

```
I20150215-12:43:35.006(8)? /Users/shawnlim/Documents/Code/meteorjs/titles/tests/cucumber/features/home.feature:11 # Scenario:
I20150215-12:43:35.006(8)?
I20150215-12:43:35.006(8)? 5 scenarios (5 failed)
I20150215-12:43:35.006(8)? 24 steps (5 failed, 19 skipped)
I20150215-12:43:38.317(8)? stream error Network error: ws://localhost:59576/websocket: connect ECONNREFUSED
I20150215-12:43:49.043(8)? stream error Network error: ws://localhost:59576/websocket: connect ECONNREFUSED
I20150215-12:43:57.336(8)? stream error Network error: ws://localhost:59576/websocket: connect ECONNREFUSED
I20150215-12:44:14.102(8)? stream error Network error: ws://localhost:59576/websocket: connect ECONNREFUSED
I20150215-12:44:16.534(8)? stream error Network error: ws://localhost:59576/websocket: connect ECONNREFUSED
I20150215-12:44:21.121(8)? stream error Network error: ws://localhost:59576/websocket: connect ECONNREFUSED
```

running ```killall node``` helps for now.

**Comment by samhatoum** [comment] 2015-02-15 09:10
That's a different issue @geekyme. I think that's actually coming from Jasmine since it's a websocket error, and Jasmine starts a mirror using freeport which usually looks like the port you're starting there. Cucumbers mirror runs on port 5000 (for now).

**Comment by Wenape** [comment] 2015-02-18 21:25
I also experience this issue occasionally (`ECONNREFUSED:-1`). Restarting my computer does fix it temporarily.

Installing the npm module or killing phantomjs doesn't work for me.

I'm on OSX 10.10, Meteor 1.0.3.1 and using xolvio:cucumber 0.3.8.

**Comment by samhatoum** [comment] 2015-02-24 19:32
could you please run with `VELOCITY_DEBUG=1 meteor` please and paste the output?

**Comment by samhatoum** [comment] 2015-03-09 16:10
This error should be fixed in the latest release. Please retest and reopen if it's still happening

**Closed by samhatoum** 2015-03-09 16:10 UTC

**Comment by geekyme** [comment] 2015-03-17 15:53
not sure if this is related. But still getting weird errors. 

```
TypeError: Cannot read property 'message' of undefined
  at [object Object].<anonymous> (/Users/shawnlim/Documents/Code/meteorjs/storyline-2.0/.meteor/local/build/programs/server/packages/xolvio_webdriver.js:442:55)
  at [object Object].emit (events.js:117:20)
  at RequestHandler.<anonymous> (/Users/shawnlim/.meteor/packages/xolvio_webdriver/.0.3.1.1bqvkny++os+web.browser+web.cordova/npm/node_modules/webdriverio/lib/utils/RequestHandler.js:164:40)
  at Request.self.callback (/Users/shawnlim/.meteor/packages/xolvio_webdriver/.0.3.1.1bqvkny++os+web.browser+web.cordova/npm/node_modules/webdriverio/node_modules/request/request.js:121:22)
  at Request.emit (events.js:98:17)
  at Request.<anonymous> (/Users/shawnlim/.meteor/packages/xolvio_webdriver/.0.3.1.1bqvkny++os+web.browser+web.cordova/npm/node_modules/webdriverio/node_modules/request/request.js:978:14)
  at Request.emit (events.js:117:20)
  at IncomingMessage.<anonymous> (/Users/shawnlim/.meteor/packages/xolvio_webdriver/.0.3.1.1bqvkny++os+web.browser+web.cordova/npm/node_modules/webdriverio/node_modules/request/request.js:929:12)
  at IncomingMessage.emit (events.js:117:20)
  at _stream_readable.js:943:16
  at process._tickDomainCallback (node.js:463:13)
```

**Comment by geekyme** [comment] 2015-03-17 15:54
Plus my cucumber tests gets repeated twice o.O 

```
I20150318-00:50:54.002(9)? 1 scenario (1 failed)
I20150318-00:50:54.002(9)? 4 steps (1 failed, 2 skipped, 1 passed)
I20150318-00:50:58.499(9)? .....
I20150318-00:50:58.500(9)?
I20150318-00:50:58.500(9)? 1 scenario (1 passed)
I20150318-00:50:58.500(9)? 4 steps (4 passed)
I20150318-00:50:58.500(9)? 2 scenarios (2 passed)
I20150318-00:50:58.500(9)? 8 steps (8 passed)
```
