### ISSUE TITLE
After sample test setup, tests endlessly load...

### ISSUE THREAD

**Issue by ksondere** [xolvio/meteor-cucumber#105] opened 2015-05-20 20:35 UTC
Using these packages

accounts-password      1.1.1  Password support for accounts
accounts-ui            1.1.5  Simple templates to add login widgets to an app
autopublish            1.0.3  Publish the entire database to all clients
insecure               1.0.3  Allow all database writes by default
iron:router            1.0.7  Routing specifically designed for Meteor
meteor-platform        1.2.2  Include a standard set of Meteor packages in your app
npm-container          1.0.0+ Contains all your npm dependencies
xolvio:cucumber        0.8.1  CucumberJS for Velocity
 
After adding xolvio:cucumber I then go to the test page and push the button to add sample tests.  The tests never load, so looking at the log here is the tail of the output.
```
at Array.forEach (native)
    at Function._.each._.forEach (/home/ksondere/.meteor/packages/velocity_meteor-tool/.1.1.3_4.p7yctk++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at Object.files.cp_r (/home/ksondere/.meteor/packages/velocity_meteor-tool/.1.1.3_4.p7yctk++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/files.js:444:5)
    at /home/ksondere/.meteor/packages/velocity_meteor-tool/.1.1.3_4.p7yctk++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/files.js:456:13
    at Array.forEach (native)
    at Function._.each._.forEach (/home/ksondere/.meteor/packages/velocity_meteor-tool/.1.1.3_4.p7yctk++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at Object.files.cp_r (/home/ksondere/.meteor/packages/velocity_meteor-tool/.1.1.3_4.p7yctk++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/files.js:444:5)
    at Command.doRunCommand [as func] (/home/ksondere/.meteor/packages/velocity_meteor-tool/.1.1.3_4.p7yctk++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/commands.js:300:11)
    at /home/ksondere/.meteor/packages/velocity_meteor-tool/.1.1.3_4.p7yctk++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/tools/main.js:1365:23
```

**Comment by samhatoum** [comment] 2015-05-20 20:37
Hey. Where is this log coming from?

Can you try to run again with `VELOCITY_DEBUG=1` please?

**Comment by samhatoum** [comment] 2015-05-20 20:37
also which platform are you running?

**Comment by samhatoum** [comment] 2015-05-21 01:47
I believe this is a duplicate of #88. Please track your issue there as I think I have found the issue

**Closed by samhatoum** 2015-05-21 01:47 UTC
