### ISSUE TITLE
Stops when running on codeship

### ISSUE THREAD

**Issue by jakobloekke** [xolvio/meteor-cucumber#25] opened 2015-01-13 07:56 UTC
I might be missing something obvious, but here goes:

I have set up some tests that work when running locally, but as soon as I try to run them as part of my Codeship test run, execution just halts at a certain point.
Here's the log:

    I20150113-07:51:40.779(0)? [xolvio:cucumber] Waiting for Velocity to start the mirror
    => Started your app.

    => App running at: http://localhost:3000/
    I20150113-07:51:41.610(0)? [velocity-mirror] [velocity-mirror] Mirror is initializing...
    I20150113-07:51:41.611(0)? 
    I20150113-07:51:42.003(0)? stream error Network error: ws://localhost:5000/websocket: connect ECONNREFUSED
    I20150113-07:51:42.015(0)? stream error Network error: ws://localhost:5000/websocket: connect ECONNREFUSED
    I20150113-07:51:42.026(0)? stream error Network error: ws://localhost:5000/websocket: connect ECONNREFUSED
    I20150113-07:51:47.939(0)? [velocity-mirror] [velocity-mirror] Mirror is ready.
    I20150113-07:51:47.939(0)? 

And then nothing happens.
Can anyone point me in a direction on how to fix this?

Thank you!

**Comment by samhatoum** [comment] 2015-01-13 19:15
someone else reported something similar and turned out to be some callback or something they missed.

Could you please try with a new blank project?

```
meteor create testApp
meteor add xolvio:cucumber
```

Then add the sample tests from the UI and get that on codeship?

**Comment by samhatoum** [comment] 2015-01-13 19:24
oh also, the error means the mirror is not able to start for some reason, you should try running with:

```
VELOCITY_DEBUG=1 meteor --test
```

**Comment by samhatoum** [comment] 2015-01-28 15:25
I think this has to do with PhantomJS. My suspicion is webdriver is trying to download a binary that doesn't work. this is related to this issue:

https://github.com/xolvio/meteor-webdriver/issues/18

**Comment by wackazong** [comment] 2015-02-20 00:55
This happens to me when I use Accounts.createUser in a fixture.

**Comment by samhatoum** [comment] 2015-02-20 02:01
If you could create a reproducible repo for me, I'll try to help

**Comment by sunkay** [comment] 2015-02-21 03:52
I agree with wackazong.. I got the same error. Removing Accounts.createUser from the fixture seems to fix the problem. 

here is a repo that can reproduce this error....
https://github.com/sunkay/meteor-boiler.git 

Thanks

**Comment by Sanjo** [comment] 2015-02-22 23:00
I think the problem is that the tests-proxy package has no dependency to the accounts packages (accounts-base, accounts-password). So Accounts is not available.

Use this approach for fixtures instead: https://github.com/xolvio/meteor-cucumber/issues/44#issuecomment-75344872. I think it will work.

**Comment by wackazong** [comment] 2015-02-22 23:24
Yep, it does. Thanks.

**Comment by samhatoum** [comment] 2015-02-24 19:45
@jakobloekke for codeship you need to also set the phantomjs path.

you should do something like this:

```
npm install -g phantomjs
export PHANTOM_PATH=`which phantomjs`
meteor --test --once
```

Let me know if this fixes the issue

**Comment by samhatoum** [comment] 2015-03-09 16:12
Fixed in latest, no need for a global phantom

**Closed** 2015-03-09 16:12 UTC
Labels: bug
